config/routes.rb
Rails.application.routes.draw do

  mount Lockup::Engine, at: "/lockup" if Rails.env.production?

  ## set a little insider variable, or clear it
  if Rails.env.development?
    get "application/set_development_mode_session_var", to: "application#set_development_mode_session_var"
    get "application/unset_development_mode_session_var", to: "application#unset_development_mode_session_var"
  end

  get    "pages/load-signatories",         to: "pages#load_signatories",        as: :load_signatories
  post   "sign/new",                       to: "sign#new",                      as: :create_signatory
  get    "sign/verify/:token",             to: "sign#verify",                   as: :verify_signatory
  get    "unsubscribe/:token",             to: "sign#unsubscribe",              as: :unsubscribe_email

  # error pages
  get "/404", to: "errors#not_found_404"
  get "/500", to: "errors#internal_error_500"
  get "/422", to: "errors#unprocessable_entity_422"

  root to: "pages#index"

end

app/views/pages/_share.html.haml
%aside.block.share
  %h2 Share it

  %nav.clear
    = link_to "mailto:?subject=Check%20out%20#{url_encode("#{Secrets.base_site_title}")}&body=#{url_encode("Sign #{Secrets.base_site_title} from #{Secrets.base_company_name}")}%0D%0A%0D%0A#{url_encode(request.original_url)}", class: "email", data: {share_type: "email"} do
      = render partial: "svg/share_box_email.svg"
    = link_to "https://www.facebook.com/sharer/sharer.php?u=#{url_encode(request.original_url)}", class: "facebook", data: {share_type: "facebook"} do
      = render partial: "svg/share_box_facebook.svg"
    = link_to "https://twitter.com/intent/tweet?text=#{url_encode("Sign #{Secrets.base_site_title} from @#{Secrets.twitter_username}:")}&url=#{url_encode(request.original_url)}&source=#{url_encode(request.original_url)}", class: "twitter", data: {share_type: "twitter"} do
      = render partial: "svg/share_box_twitter.svg"
    = link_to "http://pinterest.com/pin/create/button/?url=#{url_encode(request.original_url)}&description=#{url_encode("Sign #{Secrets.base_site_title} from #{Secrets.base_company_name}")}&media=null", class: "pinterest", data: {share_type: "pinterest"} do
      = render partial: "svg/share_box_pinterest.svg"
    = link_to "https://plus.google.com/share?url=#{url_encode(request.original_url)}", class: "google", data: {share_type: "google"} do
      = render partial: "svg/share_box_google.svg"
    = link_to "http://www.tumblr.com/share/link?url=#{url_encode(request.original_url)}&name=#{url_encode("Sign #{Secrets.base_site_title} from #{Secrets.base_company_name}")}", class: "tumblr", data: {share_type: "tumblr"} do
      = render partial: "svg/share_box_tumblr.svg"
    = link_to "http://reddit.com/submit?url=#{url_encode(request.original_url)}&title=#{url_encode("Sign #{Secrets.base_site_title} from #{Secrets.base_company_name}")}", class: "reddit", data: {share_type: "reddit"} do
      = render partial: "svg/share_box_reddit.svg"
    = link_to "http://www.linkedin.com/shareArticle?mini=true&url=#{url_encode(request.original_url)}&title=#{url_encode("Sign #{Secrets.base_site_title} from #{Secrets.base_company_name}")}", class: "linkedin", data: {share_type: "linkedin"} do
      = render partial: "svg/share_box_linkedin.svg"

app/views/pages/_sign.html.haml
%section.block.sign#sign
  %h2 Sign the Bill of Rights

  .form_holder
    =render partial: "sign_form"

  %p.press= link_to "Press Inquiries", "https://#{Secrets.parent_url}/wtf/about/press/", target: "_blank"
  %h2= link_to "Visit Ello", "https://#{Secrets.parent_url}"

app/views/pages/_sign_form.html.haml
=form_for :signatory, url: create_signatory_path, html: {class: "column three clear", remote: true} do |form|
  -if @signatory.present? && @signatory.errors.present?
    %ul.errors_list
      = render partial: 'layouts/form_error', collection: @signatory.errors.full_messages, as: :error

  %p
    =form.label "name"
    =form.text_field "name", class: "text_field", data: {validates: "presence"}
    %span.note Your name

  %p
    =form.label "website"
    =form.text_field "website", class: "text_field", data: {validates: "url"}
    %span.note Your website (optional)

  %p
    =form.label "email"
    =form.email_field "email", class: "text_field", data: {validates: "presence email"}
    %span.note Your email address (for verification only*)
    
  %p=form.button "Sign It", class: "button"

  %p.footnote * Your email address will only be used to verify your signature. It will not be shared or sold to anyone.

app/views/pages/_signatories.html.haml
%section.block.signatories.clear#signatories
  %h2.signatories Signatories
  %h2.stats= @num_signatures

  %ul.clear{style: 'display:none'}
  %p.load_more_link{style: 'display:none'}
  
  %p.loading= link_to "Loading…", load_signatories_path, remote: true

app/views/pages/_signatory.html.haml
%li
  -if signatory.website.present?
    = link_to signatory.name, "http://#{signatory.website}", target: "_blank"
  -else
    = signatory.name

app/views/pages/_signed_modal.html.haml
%aside#modal{style: 'display:none'}
  %p.close_modal
    = link_to "/" do
      %span.icon= render partial: "svg/x_icon.svg"
      %span.label Close
  .modal_content
    %h3 Thank you for signing!
    %h3 Almost finished… Check your inbox to confirm your signature.

app/views/pages/index.html.haml
%article.content
  %p.intro
    %em TO ENCOURAGE 
    an atmosphere of responsibility and transparency, while creating the most positive social network experience, Ello has created this bill of rights for all social network users.
  %p.intro.big We believe:

  %ol.points#points
    %li
      %span.bullet I
      %span.point You have the right to privacy.
      %span.content Data about you should not be collected without your knowledge and consent. Data about you should not be bought, or sold to third parties.
    %li
      %span.bullet II
      %span.point You have the right not to be tracked.
      %span.content You should be able to turn off tracking when you use a social network.

    %li
      %span.bullet III
      %span.point You have the right to control what you see.
      %span.content You should never be forced to see ads or boosted posts from people and companies that you haven’t chosen to follow. 

    %li
      %span.bullet IV
      %span.point Your followers have the right to see everything you post publicly.
      %span.content What you see should not be controlled by algorithms that favor paid posts by advertisers over friends. Everyone that follows you should see everything you post for free.

    %li
      %span.bullet V
      %span.point You have the right to own what you post.
      %span.content You should not give up ownership of the things that you create when you post them on a social network.

    %li
      %span.bullet VI
      %span.point You have the right to be anyone you want.
      %span.content You’re safest when you control what you disclose on a social network. You should not be required to give your real name, age, sex, race, marital status, sexual orientation, religion, education, home address, or any other personal information which could be sold to third parties.

    %li
      %span.bullet VII
      %span.point You have the right to relationships that won’t be exploited.
      %span.content When a social network uses your network of friends to sell things, they violate your trust.

    %li
      %span.bullet VIII
      %span.point You have the right to clear and transparent terms & conditions.
      %span.content Terms should be written in simple language that you can understand.

    %li
      %span.bullet IX
      %span.point You have the right to see all the data collected about you.
      %span.content When a social network builds a secret dossier that you don’t have access to, it violates your privacy and threatens civil rights. Downloading your data should be as easy as clicking a button.

    %li
      %span.bullet X
      %span.point You have the right to permanently delete your account.
      %span.content Leaving your social network should be simple, hassle-free, and permanent.
=render partial: "sign"
=render partial: "share"
=render partial: "signatories"

app/views/pages/load_signatories.js.erb
var signatories_html;
var next_link_html;

signatories_html = "<%= j render partial: 'signatory', collection: @signatories %>";
next_link_html = "<%=  j link_to_next_page @signatories, 'Load More Signatories', remote: true %>";

ElloBORPages.loadMoreSignatories(signatories_html, next_link_html);